services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: my_database  
    volumes:
      - D:\WorkSpace\private_cloud\mongo_db:/data/db
    ports:
      - "27017:27017"

  admin:
    image: admin-service:latest  
    container_name: admin-service
    ports:
      - "3000:3000"              
    environment:
      - APP_PORT=3000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/my_database?authSource=admin
      - NODE_ENV=production
    depends_on:
      - mongodb
    restart: unless-stopped


  auth:
    image: auth-service:latest  
    container_name: auth-service
    ports:
      - "3001:3001"              
    environment:
      - APP_PORT=3001
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/my_database?authSource=admin
      - NODE_ENV=production
    depends_on:
      - mongodb
    restart: unless-stopped
    
  user:
    image: user-service:latest  
    container_name: user-service
    ports:
      - "3002:3002"              
    environment:
      - APP_PORT=3002
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/my_database?authSource=admin
      - NODE_ENV=production
    depends_on:
      - mongodb
    restart: unless-stopped

  api:
    image: api-service:latest  
    container_name: api-service
    ports:
      - "3003:3003"              
    environment:
      - APP_PORT=3003
      - NODE_ENV=production
      - USER_SERVICE_URL=http://user-service:3002
      - AUTH_SERVICE_URL=http://auth-service:3001
    restart: unless-stopped