services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: my_database  
    volumes:
      - D:\WorkSpace\private_cloud\mongo_db:/data/db
    ports:
      - "27017:27017"

  admin:
    image: admin-service:latest  
    container_name: admin-service
    ports:
      - "4000:4000"              
    environment:
      - APP_PORT=4000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/my_database?authSource=admin
      - NODE_ENV=production
    depends_on:
      - mongodb
    restart: unless-stopped


  auth:
    image: auth-service:latest  
    container_name: auth-service
    ports:
      - "5000:5000"              
    environment:
      - APP_PORT=5000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/my_database?authSource=admin
      - NODE_ENV=production
    depends_on:
      - mongodb
    restart: unless-stopped
    